#! python 
# -*- coding: utf-8 -*-
# 

# Autogenerated by Coventor SEMulator3D on 8/22/2026, 12:29:43
# SEMulator3D 

# Using model file:        D:\Sit-lab\U24EV057\LAB1\managerworkspace\lab1.zam
# Using process file:      D:/Sit-lab/U24EV057/LAB1/managerworkspace/lab1-Input/lab1_process.vproc
# Using analysis file:     D:/Sit-lab/U24EV057/LAB1/managerworkspace/lab1-Input
# Using material file:     D:/Sit-lab/U24EV057/LAB1/managerworkspace/lab1-Input/SEMulator3DMaterialsDatabase8.vmpd
# Using layout file:       D:/Sit-lab/U24EV057/LAB1/managerworkspace/lab1-Input/pattern_u24ev057.gds

# ============================================================== 
# Command line arguments
import sys
import getopt
from voxelDocument import MonitorKillFile

opts, args = getopt.getopt(sys.argv[1:], '', ["fpw=","mpw=","spw=","encrypted","killFile="])

fpw, mpw, spw = '', '', ''
encrypted = False
for opt, arg in opts:
   if opt == "--fpw":
      fpw = arg
   elif opt == "--mpw":
      mpw = arg
   elif opt == "--spw":
      spw = arg
   elif opt == "--encrypted":
      encrypted = True
   elif opt == "--killFile":
      MonitorKillFile(arg)
# ============================================================== 
# Choose our python API version
_SEMulator3D_API_VERSION = '13.1'

# ============================================================== 
# Import Python built-in modules
import math
import time
import traceback
import logging

# Import SEMulator3D modules
from voxelModeler import *

# Initialize MPI
from CModeler import mpiInitialize
from CModeler import mpiFinalize
from subprocess import Popen
import sys
mpiInitialize(len(sys.argv), sys.argv)
# Logging
_log = logging.getLogger("cov.modelBuilding")
startTime = time.time()

#============================================================== 
# Setup Masks 
layoutFile = 'D:/Sit-lab/U24EV057/LAB1/managerworkspace/lab1-Input/pattern_u24ev057.gds'
layoutTopCell = 'pattern_u24ev057'

# GDS layer map info
layerMap = {}
layerMap['boundry'] = (0, 0)
layerMap['layer_b1'] = (1, 0)
layerMap['layer_b2'] = (2, 0)
layerMap['layer_b3'] = (3, 0)
layerMap['saparator'] = (4, 0)


#============================================================== 
# Setup Modeler and Documents
modelResolution = 2
modelUnits = 'nm'

voxDoc = VoxelDocument('D:/Sit-lab/U24EV057/LAB1/managerworkspace/lab1.zam', modelResolution, modelUnits, LOAD)

modeler = VoxelModeler(voxDoc)

# Active masks in the process
activeLayoutMaskNames = ('Rx', 'boundry', 'layer_b1', )
maskFile = MaskFile(layoutFile, layoutTopCell)

modeler.SetDefaultMaskUnitsPerMicron(maskFile.GetUnitsPerMicron())

for maskName in activeLayoutMaskNames:
    if maskName in layerMap.keys():
        mask = maskFile.GetLayerWithDataType(layerMap[maskName][0], layerMap[maskName][1])
        mask.SetName(maskName)
        modeler.AddActiveMask(mask)

# Fix build boundary based on current masks.
modeler.CacheBuildBoundary()


#============================================================== 
# Load Process 
procDoc = CProcessData.ProcessDocument()
procDoc.openWithPasswords('D:/Sit-lab/U24EV057/LAB1/managerworkspace/lab1-Input/lab1_process.vproc', fpw, mpw, encrypted)

#============================================================== 
# Load Analysis 
analysisDoc = None

#============================================================== 
# Setup Materials and Dopants
matDoc = CMaterialData.MaterialDocument()
matDoc.openWithPasswords('D:/Sit-lab/U24EV057/LAB1/managerworkspace/lab1-Input/SEMulator3DMaterialsDatabase8.vmpd', fpw, mpw, encrypted)
for mat in matDoc.getActiveMaterialsInProcess(procDoc):
    voxDoc.GetMaterials().Add(mat, DUP_ADD_ALLOW)

for dopant in matDoc.getActiveDopantsInProcess(procDoc):
    voxDoc.GetDopants().Add(dopant, DUP_ADD_ALLOW)

if analysisDoc:
    for mat in matDoc.getActiveMaterialsInProcess(analysisDoc):
        voxDoc.GetMaterials().Add(mat, DUP_ADD_ALLOW)
    
    for dopant in matDoc.getActiveDopantsInProcess(analysisDoc):
        voxDoc.GetDopants().Add(dopant, DUP_ADD_ALLOW)

success = voxDoc.GetProperties().IsModelBuildComplete() #True

#============================================================== 
# Build Model
success = modeler.BuildModel(procDoc, analysisDoc, spw)

#============================================================== 
# Save Model Build
if not voxDoc.IsOutputEnabled():
    modeler.SaveFinalStep()

voxDoc.GetProperties().SetModelBuildComplete(success)
voxDoc.Save()

endTime = time.time()
_log.info('Build process completed.')
_log.info('Elapsed Time %d seconds.', (endTime-startTime))
mpiFinalize()

if voxDoc.GetProperties().GetStartViewer():
    Popen(['SEMulator3DViewer','D:/Sit-lab/U24EV057/LAB1/managerworkspace/lab1.zam','-standalone:false'], env=os.environ)

if not success:
    # Though the build terminated cleanly, it was not considered successful.
    sys.exit(1)

